---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
world_df <- read.csv("https://raw.githubusercontent.com/plotly/datasets/master/2014_world_gdp_with_codes.csv")
country_df <- read_csv("data/country_conv.csv")
population_df <- read_csv("data/world_population.csv") 
names(population_df) <- sub(" ", "_", names(population_df))
energy_data <- read_csv("data/world_energy.csv")
energy_data <- energy_data %>% filter(energy_type != "total" & energy_type != "all_renewable")
energy_data <- energy_data %>% filter(country_code != "WORL")
energy <- left_join(energy_data, country_df, by = "country_code")
energy <- left_join(energy, population_df, by = c("year" = "Year", "country_code" = "Country_Code", "country" = "Country_Name"))
energy_world_df <- left_join(world_df, energy, by = c("CODE" = "country_code", "COUNTRY" = "country")) %>% select(-GDP..BILLIONS.)
names(energy_world_df)[1] <- "country_name"
names(energy_world_df)[2] <- "country_code"
names(energy_world_df)[6] <- "population"
#plot_ly(energy_world_df, type='choropleth', locations=~country_code, z=~energy, text = ~country_name)
```
```{r}

energy_world_df_top_10 <- energy_world_df %>% filter(year == 1982) %>% group_by(energy_type, country_name) %>% summarise(energy_consumption = sum(energy, na.rm = TRUE)) %>% arrange(desc(energy_consumption))
energy_world_df_top_10 <- energy_world_df_top_10 %>% filter(energy_type == "coal") %>% slice_max(energy_consumption, n = 10)
energy_world_df_top_10

ggplot(energy_world_df_top_10, aes(y = reorder(country_name, energy_consumption), x = energy_consumption, fill = country_name)) +
  geom_bar(stat = "identity") 
```

